// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3wuA8q8GnXRLUdfVcjMGEd8sB4bUS6sI',
    appId: '1:283418907529:web:bf9d70267020dd5c9d8758',
    messagingSenderId: '283418907529',
    projectId: 'practica-edteam',
    authDomain: 'practica-edteam.firebaseapp.com',
    storageBucket: 'practica-edteam.appspot.com',
    measurementId: 'G-TN5JHDX9ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALzRPsEkfkGgQTtpesmaUWqhbOCMblkDQ',
    appId: '1:283418907529:android:6733ad98589a2ed99d8758',
    messagingSenderId: '283418907529',
    projectId: 'practica-edteam',
    storageBucket: 'practica-edteam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCvqGIi8Mbqtyl3Xbfg8M0AV6EBYs5OBY',
    appId: '1:283418907529:ios:9d5f6b619846897d9d8758',
    messagingSenderId: '283418907529',
    projectId: 'practica-edteam',
    storageBucket: 'practica-edteam.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCvqGIi8Mbqtyl3Xbfg8M0AV6EBYs5OBY',
    appId: '1:283418907529:ios:eccc0dccc8b1170d9d8758',
    messagingSenderId: '283418907529',
    projectId: 'practica-edteam',
    storageBucket: 'practica-edteam.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
